export type ThemeMaterial = 'ultraThinMaterial' | 'thinMaterial' | 'regularMaterial' | 'bar'
export type ThemeAppearance = 'light' | 'dark'

export interface ThemeTokens {
  appBackground: string
  backgroundGradient: [string, string, string]
  ambientBlobColors: [string, string, string]
  glassMaterial: ThemeMaterial
  glassFill: string
  glassFillStrong: string
  glassStroke: string
  glassHighlight: string
  glassShadow: string
  textPrimary: string
  textSecondary: string
  textMuted: string
  textDisabled: string
  accentPrimary: string
  accentSecondary: string
  success: string
  warning: string
  danger: string
  selection: string
  focusRing: string
  buttonGradient: [string, string]
  fontDisplay: string
  fontBody: string
  fontCaption: string
  fontMono: string
  cornerRadiusCard: number
  cornerRadiusButton: number
  cornerRadiusPanel: number
}

export interface AppTheme {
  id: string
  name: string
  mood: string
  appearance: ThemeAppearance
  tokens: ThemeTokens
}

const FONT_SF_DISPLAY = '"SF Pro Display", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
const FONT_SF_ROUNDED = '"SF Pro Rounded", "SF Pro Display", -apple-system, BlinkMacSystemFont, sans-serif'
const FONT_SF_BODY = '"SF Pro Text", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
const FONT_NEW_YORK = '"New York", ui-serif, Georgia, serif'
const FONT_MONO = '"SF Mono", "SFMono-Regular", ui-monospace, Menlo, Monaco, monospace'

const DEFAULT_CARD_RADIUS = 22
const DEFAULT_BUTTON_RADIUS = 14
const DEFAULT_PANEL_RADIUS = 28

function createTheme(theme: AppTheme): AppTheme {
  return theme
}

export const APP_THEMES = [
  createTheme({
    id: 'tolariaDawn',
    name: 'Tolaria Dawn',
    mood: 'Warm compatibility light theme with softened glass for bright workspaces',
    appearance: 'light',
    tokens: {
      appBackground: '#F5EFE6',
      backgroundGradient: ['#F2E9DD', '#F7F1E8', '#ECE4D9'],
      ambientBlobColors: ['#FFC58F44', '#649CFF2E', '#FFDEBE38'],
      glassMaterial: 'ultraThinMaterial',
      glassFill: '#FFF8F1C6',
      glassFillStrong: '#FFFDF8DD',
      glassStroke: '#8B6C5533',
      glassHighlight: '#FFFFFFA3',
      glassShadow: '#11182733',
      textPrimary: '#28211C',
      textSecondary: '#6F665E',
      textMuted: '#8F8377',
      textDisabled: '#B09F90',
      accentPrimary: '#2363FF',
      accentSecondary: '#7C5BD6',
      success: '#2D9B69',
      warning: '#D97724',
      danger: '#DC4A43',
      selection: '#2363FF1F',
      focusRing: '#4D84FF',
      buttonGradient: ['#2363FF', '#7C5BD6'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'obsidianAurora',
    name: 'Obsidian Aurora',
    mood: 'Premium futuristic AI/productivity dashboard',
    appearance: 'dark',
    tokens: {
      appBackground: '#05070D',
      backgroundGradient: ['#05070D', '#0B1020', '#101A2F'],
      ambientBlobColors: ['#22D3EE30', '#8B5CF630', '#10B98122'],
      glassMaterial: 'ultraThinMaterial',
      glassFill: '#FFFFFF10',
      glassFillStrong: '#FFFFFF17',
      glassStroke: '#FFFFFF24',
      glassHighlight: '#FFFFFF40',
      glassShadow: '#00000080',
      textPrimary: '#F8FAFC',
      textSecondary: '#B6C2D1',
      textMuted: '#78849A',
      textDisabled: '#566072',
      accentPrimary: '#22D3EE',
      accentSecondary: '#A78BFA',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#FB7185',
      selection: '#22D3EE33',
      focusRing: '#67E8F9',
      buttonGradient: ['#22D3EE', '#8B5CF6'],
      fontDisplay: FONT_SF_ROUNDED,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'graphiteSapphire',
    name: 'Graphite Sapphire',
    mood: 'Native macOS professional calm durable',
    appearance: 'dark',
    tokens: {
      appBackground: '#07090C',
      backgroundGradient: ['#07090C', '#10151D', '#111827'],
      ambientBlobColors: ['#0A84FF24', '#60A5FA1F', '#94A3B818'],
      glassMaterial: 'regularMaterial',
      glassFill: '#EAF2FF0D',
      glassFillStrong: '#EAF2FF16',
      glassStroke: '#D8E7FF22',
      glassHighlight: '#FFFFFF35',
      glassShadow: '#00000070',
      textPrimary: '#F5F7FA',
      textSecondary: '#C3CBD6',
      textMuted: '#8792A2',
      textDisabled: '#5D6673',
      accentPrimary: '#0A84FF',
      accentSecondary: '#64D2FF',
      success: '#30D158',
      warning: '#FFD60A',
      danger: '#FF453A',
      selection: '#0A84FF33',
      focusRing: '#64D2FF',
      buttonGradient: ['#0A84FF', '#64D2FF'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'midnightPlum',
    name: 'Midnight Plum',
    mood: 'Elegant creative writing/media app',
    appearance: 'dark',
    tokens: {
      appBackground: '#090611',
      backgroundGradient: ['#090611', '#160B25', '#241036'],
      ambientBlobColors: ['#D946EF24', '#8B5CF62E', '#F472B61C'],
      glassMaterial: 'thinMaterial',
      glassFill: '#F5D0FE10',
      glassFillStrong: '#F5D0FE18',
      glassStroke: '#F5D0FE26',
      glassHighlight: '#FFFFFF38',
      glassShadow: '#00000078',
      textPrimary: '#FAF7FF',
      textSecondary: '#D8CFE8',
      textMuted: '#9C8DAF',
      textDisabled: '#665876',
      accentPrimary: '#C084FC',
      accentSecondary: '#F0ABFC',
      success: '#86EFAC',
      warning: '#FDE68A',
      danger: '#FDA4AF',
      selection: '#C084FC33',
      focusRing: '#F0ABFC',
      buttonGradient: ['#A855F7', '#EC4899'],
      fontDisplay: FONT_NEW_YORK,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'blackEmerald',
    name: 'Black Emerald',
    mood: 'Security finance terminal-adjacent premium dark',
    appearance: 'dark',
    tokens: {
      appBackground: '#030806',
      backgroundGradient: ['#030806', '#07140F', '#0B1F17'],
      ambientBlobColors: ['#10B9812E', '#14F19522', '#2DD4BF1A'],
      glassMaterial: 'regularMaterial',
      glassFill: '#D1FAE50E',
      glassFillStrong: '#D1FAE518',
      glassStroke: '#A7F3D026',
      glassHighlight: '#FFFFFF32',
      glassShadow: '#00000082',
      textPrimary: '#F1FFF8',
      textSecondary: '#BFE7D4',
      textMuted: '#7BA895',
      textDisabled: '#4F6D60',
      accentPrimary: '#34D399',
      accentSecondary: '#2DD4BF',
      success: '#22C55E',
      warning: '#FACC15',
      danger: '#F87171',
      selection: '#34D39930',
      focusRing: '#6EE7B7',
      buttonGradient: ['#10B981', '#2DD4BF'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'polarNoir',
    name: 'Polar Noir',
    mood: 'Minimal icy clean SaaS/mac utility',
    appearance: 'dark',
    tokens: {
      appBackground: '#06080B',
      backgroundGradient: ['#06080B', '#0B1117', '#101820'],
      ambientBlobColors: ['#BAE6FD20', '#E0F2FE18', '#CBD5E11C'],
      glassMaterial: 'ultraThinMaterial',
      glassFill: '#E0F2FE0F',
      glassFillStrong: '#E0F2FE18',
      glassStroke: '#E0F2FE2A',
      glassHighlight: '#FFFFFF48',
      glassShadow: '#0000006E',
      textPrimary: '#F8FBFF',
      textSecondary: '#C9D6E2',
      textMuted: '#8EA0AF',
      textDisabled: '#5E6B77',
      accentPrimary: '#7DD3FC',
      accentSecondary: '#38BDF8',
      success: '#86EFAC',
      warning: '#FDE68A',
      danger: '#FDA4AF',
      selection: '#7DD3FC2E',
      focusRing: '#BAE6FD',
      buttonGradient: ['#7DD3FC', '#38BDF8'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'solarEmber',
    name: 'Solar Ember',
    mood: 'Warm dark creator tools energetic but not harsh',
    appearance: 'dark',
    tokens: {
      appBackground: '#0C0503',
      backgroundGradient: ['#0C0503', '#1A0D08', '#29130B'],
      ambientBlobColors: ['#FB923C2B', '#F9731627', '#FACC1518'],
      glassMaterial: 'thinMaterial',
      glassFill: '#FFF7ED0F',
      glassFillStrong: '#FFF7ED18',
      glassStroke: '#FED7AA29',
      glassHighlight: '#FFFFFF36',
      glassShadow: '#00000078',
      textPrimary: '#FFF8F1',
      textSecondary: '#E8CDB8',
      textMuted: '#A98268',
      textDisabled: '#6D5547',
      accentPrimary: '#FB923C',
      accentSecondary: '#FACC15',
      success: '#84CC16',
      warning: '#FDBA74',
      danger: '#F43F5E',
      selection: '#FB923C30',
      focusRing: '#FDBA74',
      buttonGradient: ['#F97316', '#FACC15'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'cyberIris',
    name: 'Cyber Iris',
    mood: 'Neon command center gaming/devtool without looking childish',
    appearance: 'dark',
    tokens: {
      appBackground: '#05030B',
      backgroundGradient: ['#05030B', '#0F0820', '#15102E'],
      ambientBlobColors: ['#6366F13A', '#06B6D42C', '#EC489923'],
      glassMaterial: 'ultraThinMaterial',
      glassFill: '#EEF2FF0D',
      glassFillStrong: '#EEF2FF17',
      glassStroke: '#C4B5FD28',
      glassHighlight: '#FFFFFF3B',
      glassShadow: '#00000085',
      textPrimary: '#F7F7FF',
      textSecondary: '#C9C7F1',
      textMuted: '#918BC3',
      textDisabled: '#615C84',
      accentPrimary: '#818CF8',
      accentSecondary: '#22D3EE',
      success: '#4ADE80',
      warning: '#FDE047',
      danger: '#F472B6',
      selection: '#818CF833',
      focusRing: '#A5B4FC',
      buttonGradient: ['#6366F1', '#22D3EE'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'deepTealStudio',
    name: 'Deep Teal Studio',
    mood: 'Design app calm editor polished utility',
    appearance: 'dark',
    tokens: {
      appBackground: '#031011',
      backgroundGradient: ['#031011', '#071A1D', '#0B2529'],
      ambientBlobColors: ['#2DD4BF28', '#38BDF824', '#A7F3D01A'],
      glassMaterial: 'regularMaterial',
      glassFill: '#CCFBF10E',
      glassFillStrong: '#CCFBF118',
      glassStroke: '#99F6E42A',
      glassHighlight: '#FFFFFF36',
      glassShadow: '#00000075',
      textPrimary: '#F0FDFA',
      textSecondary: '#B9E4DF',
      textMuted: '#7DA8A2',
      textDisabled: '#52706C',
      accentPrimary: '#2DD4BF',
      accentSecondary: '#38BDF8',
      success: '#22C55E',
      warning: '#FBBF24',
      danger: '#FB7185',
      selection: '#2DD4BF30',
      focusRing: '#5EEAD4',
      buttonGradient: ['#14B8A6', '#38BDF8'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'rubyCarbon',
    name: 'Ruby Carbon',
    mood: 'Bold cinematic pro creative suite',
    appearance: 'dark',
    tokens: {
      appBackground: '#080506',
      backgroundGradient: ['#080506', '#16090D', '#230D14'],
      ambientBlobColors: ['#E11D4833', '#FB718524', '#F43F5E20'],
      glassMaterial: 'thinMaterial',
      glassFill: '#FFE4E60E',
      glassFillStrong: '#FFE4E618',
      glassStroke: '#FDA4AF28',
      glassHighlight: '#FFFFFF34',
      glassShadow: '#00000082',
      textPrimary: '#FFF7F8',
      textSecondary: '#E6C3C9',
      textMuted: '#A77B85',
      textDisabled: '#6F5259',
      accentPrimary: '#FB7185',
      accentSecondary: '#F43F5E',
      success: '#4ADE80',
      warning: '#FBBF24',
      danger: '#FF375F',
      selection: '#FB718530',
      focusRing: '#FDA4AF',
      buttonGradient: ['#E11D48', '#FB7185'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'champagneSmoke',
    name: 'Champagne Smoke',
    mood: 'Luxury notes CRM boutique productivity',
    appearance: 'dark',
    tokens: {
      appBackground: '#080705',
      backgroundGradient: ['#080705', '#15120D', '#211B13'],
      ambientBlobColors: ['#FDE68A20', '#D6A85D24', '#FFFFFF10'],
      glassMaterial: 'regularMaterial',
      glassFill: '#FFF7ED10',
      glassFillStrong: '#FFF7ED18',
      glassStroke: '#FDE68A24',
      glassHighlight: '#FFFFFF42',
      glassShadow: '#00000076',
      textPrimary: '#FFFDF7',
      textSecondary: '#E3D6BF',
      textMuted: '#A89A82',
      textDisabled: '#6E6252',
      accentPrimary: '#FDE68A',
      accentSecondary: '#D6A85D',
      success: '#A7F3D0',
      warning: '#FBBF24',
      danger: '#FCA5A5',
      selection: '#FDE68A26',
      focusRing: '#FDE68A',
      buttonGradient: ['#D6A85D', '#FDE68A'],
      fontDisplay: FONT_NEW_YORK,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'monoGraphite',
    name: 'Mono Graphite',
    mood: 'Developer tool logs database no-nonsense',
    appearance: 'dark',
    tokens: {
      appBackground: '#050505',
      backgroundGradient: ['#050505', '#0D0D0F', '#17181A'],
      ambientBlobColors: ['#94A3B81A', '#38BDF818', '#FFFFFF0D'],
      glassMaterial: 'regularMaterial',
      glassFill: '#FFFFFF0C',
      glassFillStrong: '#FFFFFF14',
      glassStroke: '#FFFFFF20',
      glassHighlight: '#FFFFFF30',
      glassShadow: '#00000080',
      textPrimary: '#F4F4F5',
      textSecondary: '#C4C4C7',
      textMuted: '#8A8A91',
      textDisabled: '#5C5C62',
      accentPrimary: '#A1A1AA',
      accentSecondary: '#38BDF8',
      success: '#22C55E',
      warning: '#EAB308',
      danger: '#EF4444',
      selection: '#A1A1AA26',
      focusRing: '#D4D4D8',
      buttonGradient: ['#52525B', '#A1A1AA'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
  createTheme({
    id: 'cosmicSlate',
    name: 'Cosmic Slate',
    mood: 'Balanced modern works for most apps',
    appearance: 'dark',
    tokens: {
      appBackground: '#060815',
      backgroundGradient: ['#060815', '#0F172A', '#1E1B4B'],
      ambientBlobColors: ['#60A5FA26', '#A78BFA22', '#F472B61A'],
      glassMaterial: 'thinMaterial',
      glassFill: '#DBEAFE0E',
      glassFillStrong: '#DBEAFE18',
      glassStroke: '#BFDBFE28',
      glassHighlight: '#FFFFFF38',
      glassShadow: '#0000007A',
      textPrimary: '#F8FAFC',
      textSecondary: '#C7D2FE',
      textMuted: '#94A3B8',
      textDisabled: '#64748B',
      accentPrimary: '#60A5FA',
      accentSecondary: '#A78BFA',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      selection: '#60A5FA30',
      focusRing: '#93C5FD',
      buttonGradient: ['#60A5FA', '#A78BFA'],
      fontDisplay: FONT_SF_DISPLAY,
      fontBody: FONT_SF_BODY,
      fontCaption: FONT_SF_BODY,
      fontMono: FONT_MONO,
      cornerRadiusCard: DEFAULT_CARD_RADIUS,
      cornerRadiusButton: DEFAULT_BUTTON_RADIUS,
      cornerRadiusPanel: DEFAULT_PANEL_RADIUS,
    },
  }),
] as const satisfies readonly AppTheme[]

export type ThemeId = (typeof APP_THEMES)[number]['id']

export const DEFAULT_THEME_ID: ThemeId = 'graphiteSapphire'

const APP_THEME_MAP = new Map(APP_THEMES.map((theme) => [theme.id, theme]))

export function isThemeId(value: unknown): value is ThemeId {
  return typeof value === 'string' && APP_THEME_MAP.has(value)
}

export function getThemeById(themeId: ThemeId): AppTheme {
  return APP_THEME_MAP.get(themeId) ?? APP_THEME_MAP.get(DEFAULT_THEME_ID)!
}

export function getThemeSelectOptions() {
  return APP_THEMES.map((theme) => ({
    value: theme.id,
    label: theme.name,
  }))
}
